all : 
	make -C assembly
	make -C templates
	make -C generator
	make -C sequence-generator
	
	
clean :
	make -C assembly clean
	make -C generator clean
	make -C sequence-generator clean
	make -C templates clean
