field qreg %rax %rcx %rdx %rbx %rbp %rsi %rdi %r8 %r9 %r10 %r11 %r12 %r13 %r14 %r15
field dreg %eax %ecx %edx %ebx %ebp %esi %edi %r8d %r9d %r10d %r11d %r12d %r13d %r14d %r15d
field wreg %ax %cx %dx %bx %bp %si %di %r8w %r9w %r10w %r11w %r12w %r13w %r14w %r15w
field breg %al %cl %dl %bl %bl %sil %dil %r8b %r9b %r10b %r11b %r12b %r13b %r14b %r15b

field qreg_div %rax %rcx %rbx %rbp %rsi %rdi %r8 %r9 %r10 %r11 %r12 %r13 %r14 %r15
field dreg_div %eax %ecx %ebx %ebp %esi %edi %r8d %r9d %r10d %r11d %r12d %r13d %r14d %r15d
field wreg_div %ax %cx %bx %bp %si %di %r8w %r9w %r10w %r11w %r12w %r13w %r14w %r15w
field breg_div %al %cl %bl %bl %sil %dil %r8b %r9b %r10b %r11b %r12b %r13b %r14b %r15b

field xmmreg %xmm0 %xmm1 %xmm2 %xmm3 %xmm4 %xmm5 %xmm6 %xmm7 %xmm8

field imm $0x0 $0x10 $0x50 $0x100
field imm8 $0x0 $0x10 $0x50 $0xff
field imm16 $0x0 $0xf0f0 $0xffff $0x1234
field imm32 $0x7ffffffe $0x7fffffff $0x12345678 $0x77654321

